## Assignment 2<br>BUSI 721<br>Data Driven Finance I<br>Jones Graduate School of Business<br>Rice University<br>

Submit a Jupyter notebook.  Copy each question into a Markdown cell and provide your answer in the cell or cells below it.

1.  Using Yahoo Finance, calculate daily, monthly, and annual returns for CVX over the five-year period Jan 1, 2018 through Dec 31, 2021.  Plot the returns.  Note: you should use start="2016-12-30" and end="2021-12-31" in the pandas datareader.  Also, for plotting it is better not to convert the index to the period format.
2.  Create box plots for the three sets of returns.
3.  What was the geometric average annual return for CVX over the five-year period?
4. Draw 1,000 sets of 30 normally distributed random variables with a mean of 6% and a standard deviation of 10%.  Viewing the variables as annual returns, compound them over each 30-year period to obtain 1,000 accumulations $(1+r_1) \cdots (1+r_{30})$.  Create a box plot of the 1,000 accumulations.  Execute np.random.seed(0) before generating the random variables.