## Assignment 1<br>BUSI 721<br>Data Driven Finance I<br>Jones Graduate School of Business<br>Rice University<br>


1. I have $50,000 now and I plan to invest $10,000 in one year and another $40,000 at the end of the following four years (five investments in five years in total).  If I earn 6% per year on my investments, what will I have at the end of the five years?

2.  I have $50,000 now and plan to invest money at the end of this year and also for the following four years (five investments in five years in total).  I expect to earn 6% per year.  I hope to have $200,000 at the end of the five years, including the last investment.  How much do I need to invest each year?  

3. What would the monthly payments be on a 5-year loan for $40,000 at 6%?

4. How much can I borrow on a 5-year loan at 6% if I can afford to pay $500 per month?

5. An investment earned 10%, 15%, -8%, -3%, and 20% over a five-year span.  Inflation over the five years was 3%, 5%, 7%, 4%, and 2%.

  a. How much did $1 at the beginning of the five years grow to in nominal terms?
  b. In real terms?

6.  An investment earned 10%, 15%, -8%, -3%, and 20% over a five-year span.  
 a. What were the corresponding continuously compounded returns?
 b. What was the sum of the continuously compounded returns?
 c. How does the natural exponential of the sum of the continuously compounded returns ($e^{\sum \ldots}$) compare to the answer to 5a?