## Assignment 4<br>BUSI 721<br>Data Driven Finance I<br>Jones Graduate School of Business<br>Rice University<br>

Submit a Jupyter notebook.  Copy each question into a Markdown cell and provide your answer in the cell or cells below it.

1.  Two stocks have standard deviations of 30%. 

  a. Plot the standard deviation of a 50-50 portfolio of the two stocks as a function of the correlation between them, for correlations between -1 and +1.
  b. Plot the Sharpe ratio of the 50-50 portfolio as a function of the correlation.  Assume both assets have expected returns of 10% and the risk-free rate (saving rate) is 2%.  Exclude the correlation of -1.

2.  Three assets have standard deviations of 20%, 30%, and 40%.  Their expected returns are 10%, 15%, and 12%.  Compute the mean and standard deviation of a portfolio that is 25% in stock 1, 50% in stock 2, and 25% in stock 3.  Plot the assets and the portfolio in mean -- standard deviation space.

3. For the data in question 2, find the least-risk portfolio with an expected return of 12%.  Assume the saving and borrowing rate are both 2%.
