## Assignment 3<br>BUSI 721<br>Data Driven Finance I<br>Jones Graduate School of Business<br>Rice University<br>

The six assignments for Module 2 are provided below.  For each python assignment, submit a Jupyter notebook on Canvas.  If there are multiple questions in an assignment, copy each question into a Markdown cell and provide your answer in the cell or cells below it.  Tor each Excel assignment, submit an Excel workbook.

For the discussion assignments, you are expected to participate in the discussion board on Canvas.

#### 3.1 Leverage (Excel Assignment)

You have a $50,000 portfolio.  You are considering levering it -- borrowing $25,000 to increase the investment to $75,000.  You can borrow at 5%.  

1) Suppose the unlevered investment earns 10% and 5% interest is rolled into your debt.  What are your assets, liabilities, and equity (equity = net portfolio value)?  What was your return on your $50,000? 

2) Repeat part (1) assuming the unlevered investment loses 10%.

#### 3.2 Short Selling (Excel Assignment)

2.  I think CVX will beat XOM.  I am considering investing $10,000, buying $10,000 of CVX, and shorting $10,000 of XOM.  I will earn negligible interest on the short sale proceeds.  What will be my gain or loss if CVX earns 12% and XOM earns 5%?  What if the reverse happens?

3.  SKIP QUESTION 3

4.  A 6% coupon bond makes semi-annual coupon payments (3% each six months).  It has 10 years to maturity, and the next coupon payment is six months away.  Its current yield is 8%.  What is its price?