---
title:  "Cash Flows and NPV"
author: <br>Kerry Back<br><br>BUSI 721, Fall 2022<br>JGSB, Rice University
output-dir: docs
execute:
  echo: false
  jupyter: python3
format: 
  revealjs:
    highlight-style: monokai
    code-fold: true
    slide-number: true
    preview-links: true
    self-contained: true
    transition: fade
    theme: [solarized, 721.scss]
    incremental: true
---

## Property, plant, & equipment

- Net PP&E = undepreciated part of historical PP&E cost
- Use tax depreciation schedules
  - Accelerated compared to straight line financial reporting

## Net working capital

- Short-term assets minus short-term operating liabilities
  - Short-term is called "current"
- Inventory plus accounts receivable minus accounts payable

## Invested capital

- Net PP&E plus net working capital
- Equals assets not financed by payables
- $\Rightarrow$ financed by investors (shareholders and lenders)
- Example: Net PP&E = 100, current assets = 30, current liabilities = 10
  - Total assets = 130
  - Invested capital = 120

## Project cash flows

- Cash flow = income minus change in invested capital
- Usual timing
  - Early years = negative cash flows (build up of capital)
  - Middle years = positive cash flows
  - End = either
    - Extra positive cash flow due to wind-down of working capital and salvage value of PP&E
    - Or maybe disposal and/or environmental clean-up costs

## Example

. . .

| Year | 0 | 1 | 2 | 3 | 4 |
|:---|---:|---:|---:|---:|---:|
| Invested capital | 100 | 70 | 50 | 35 | 0 |
 Income | 0 | 20 | 30 | 20 | 5 |

. . .

<br>

| Year | 0 | 1 | 2 | 3 | 4 |
|:---|---:|---:|---:|---:|---:|
 Income | 0 | 20 | 30 | 20 | 5 |
| Change in invested capital | 100 | -30 | -20 | -15 | -35 |
| Cash flow | -100 | 50 | 50 | 35 | 40 |



## Example in code

. . .

```{.p code-line-numbers="1-5|6-8|10"}
import numpy as np
import pandas as pd

IC = pd.Series((100, 70, 50, 35, 0))
Income = pd.Series((0, 20, 30, 20, 5))
df = pd.concat((IC, Income), axis=1)
df.columns = ["IC", "Income"]
df.index.name = "Year"

df.T
```

. . .

```{python}
import numpy as np
import pandas as pd

IC = pd.Series((100, 70, 50, 35, 0))
Income = pd.Series((0, 20, 30, 20, 5))
df = pd.concat((IC, Income), axis=1)
df.columns = ["IC", "Income"]
df.index.name = "Year"

df.T
```

#

```{.p code-line-numbers="1-2|3|5"}
df["Change in IC"] = df.IC.diff()
df["Change in IC"].iloc[0] = df["IC"].iloc[0]
df["Cash flow"] = df.Income - df["Change in IC"]

df.T
```
. . .

```{python}
df["Change in IC"] = df.IC.diff()
df["Change in IC"].iloc[0] = df["IC"].iloc[0]
df["Cash flow"] = df.Income - df["Change in IC"]

df.T
```


## Net present value

```{.p code-line-numbers="1|3|4|5-6|8"}
cost_capital = 0.1

df["PV factor"] = 1 / (1+cost_capital)**df.index
df["PV of cash flow"] = df["Cash flow"] * df["PV Factor"]
df["NPV"] = np.nan
df["NPV"].iloc[0] = df["PV of cash flow"].sum()

df[["Cash flow", "PV factor", "PV of cash flow", "NPV"]].T
```

. . .

```{python}
cost_capital = 0.1
df["PV factor"] = 1 / (1+cost_capital)**df.index
df["PV of cash flow"] = df["Cash flow"] * df["PV factor"]
df["NPV"] = np.nan
df["NPV"].iloc[0] = df["PV of cash flow"].sum()

df[["Cash flow", "PV factor", "PV of cash flow", "NPV"]].T.round(2)
```



 
