---
title:  "Financial Accounting"
author: <br>BUSI 721, Fall 2022<br>JGSB, Rice UniversityKerry Back<br><br>
output-dir: docs
execute:
  echo: false
  jupyter: python3
format: 
  revealjs:
    highlight-style: monokai
    code-fold: true
    slide-number: true
    preview-links: true
    self-contained: true
    transition: fade
    theme: [solarized, 721.scss]
    incremental: true
---

## Timing of expenses

- Match expenses with corresponding sales.  Deduct when you record income.
- Raw materials are inventories, not expenses.
- Same for labor cost of goods in process.
- Materials + labor charged against sales when sales occur.
- Build-up of inventory is an increase in invested capital and a negative cash flow.

## Timing of income

- Record sales when they occur (or on delivery) not when receivable is collected.
- A sale that is not collected is a build-up of invested capital (accounts receivable).
  - Record sale in income statement.
  - Offset it in cash flows with build-up of invested capital
- Pre-payment of sales is recorded as a liability.
  - Increase in liability is a reduction in invested capital.
  - Cash from prepayment shows up not in income but as reduction in invested capital.

## Property, plant & equipment

- IRS requires investment in "long-term assets" to be expensed (depreciated) over time.
- Not expensed against corresponding sales. Timing of sales is irrelevant. 
- Not expensed according to your own beliefs about how long the assets will last.
- Fixed schedules for different types of assets
- MACRS = Modified Accelerated Cost Recovery System: [Wikipedia](https://en.wikipedia.org/wiki/MACRS) 

## Depreciation and income

- Depreciation shows up as a cost in the income statement
- Reduces taxable income, so reduces taxes
- It is not a cash outflow.
- Depreciation is a reduction in invested capital, which offsets the cost shown in the income statement.
- Only effect of depreciation on cash flows is tax shield.

## Disposal of PP&E

- Selling equipment produces a taxable gain or loss
- Is also a reduction in invested capital
- Selling price minus book value minus taxes goes in income statement
- Subtracting reduction in invested capital adds back the book value to cash flow
- Net effect on cash flow is selling price minus taxes

## Example

- Project requires $10 million purchase of 5-year MACRS equipment.  Depreciation rates are 20%, 32%, 19.2%, 11.52%, 11.52% and 5.76%.
- Anticipate equipment could be sold for $3 million at end of year 5.
- Project sales revenue of $6, $10, $12, $10, and $5 million

# 

- Cost of goods sold (materials + labor) = 50% of sales
- Initial working capital of $0.5 million (inventory), thereafter 20% of COGS, but 0 in year 5
- Selling, general & administrative expenses of $2, $2, $1, $1, and $1 million
- Corporate tax rate (state + federal) is 30%
- Discount rate is 10%
